remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Jorge Romero
show_downloads: false
description: Enthusiastic student dedicated to academic excellence, with a passion for learning from diverse sources—avidly reading, listening, and absorbing knowledge from books and people alike
